# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ipa-threat2025

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://crvistapoc.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca32df6bdaac4f8a86dd57a342f52b67 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d0f7e5e367d7429ab98b0119d0165e8c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: crvistapoc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca32df6bdaac4f8a86dd57a342f52b67 }}/ipa-threat2025:${{ github.sha }}
        file: ./WebApp.Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ipa-threat2025'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fec47159479f4d6e802ae0cb659fb16d }}
        images: 'crvistapoc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca32df6bdaac4f8a86dd57a342f52b67 }}/ipa-threat2025:${{ github.sha }}'